image: ubuntu

variables:
  SOME_VAR: "some value"
  SONAR_TOKEN: "b59093f5200cd1a7575092c434998e3c3b0fc0a2"

stages:
  - build
  - whereami
  - test
  - sonarqube
  - deploy

before_script:
  - echo "Start CI/CD"
  - echo "SOME_VAR = $SOME_VAR" # calls my custom variable
  - echo $CI_JOB_STAGE  # calls a predefined variable -  https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
  - echo $CI_COMMIT_SHORT_SHA # calls another predefined variable

# build:
#   stage: build
#   script:
#     - echo "Build process"
#     - cd Inquirist
#     - chmod +x mvnw
#     - ./mvnw -N wrapper:wrapper
#     - ./mvnw clean install
#     - echo "Build ok"
#   only:
#     - main
#   tags:
#     - alpine-docker
#   artifacts:
#     paths:
#       - target/*.jar



# sonarqube:
#   stage: sonarqube
#   script:
#     - echo "start sonarqube stage"
#     - ls
#     - cd Inquirist
#     - chmod +x mvnw
#     - ./mvnw verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=0:0
#     - echo "sonarqube ok"
#   only:
#     - main
#   tags:
#     - alpine-docker

deploy_ssh:
  stage: deploy
  before_script:
    - ssh
    - apt-get install openssh-client -y
    - echo "$SSH_PRIVATE_KEY" 
  script:
    - echo "deploy apps"
    - ssh -i $SSH_PRIVATE_KEY $SSH_USER@$SSH_HOST 'echo helloworld'
    - echo "deploy ok"
  only:
    - main
  tags:
    - alpine-docker
  # when: manual

after_script:
  - echo "End CI/CD"
