image: ubuntu

variables:
  SOME_VAR: "some value"

stages:
  - build
  - whereami
  - test
  - sonarqube
  - deploy

before_script:
  - echo "Start CI/CD"
  - echo "SOME_VAR = $SOME_VAR" # calls my custom variable
  - echo $CI_JOB_STAGE  # calls a predefined variable -  https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
  - echo $CI_COMMIT_SHORT_SHA # calls another predefined variable

build:
  image: maven:3-jdk-8
  stage: build
  script:
    - echo "Build process"
    - java -version
    - cd Inquirist
    - chmod +x mvnw
    - ./mvnw -N wrapper:wrapper
    - ./mvnw clean install
    - echo "Build ok"
  only:
    - main
  tags:
    - alpine-docker
  artifacts:
    paths:
      - target/*.jar

whereami:
  stage: whereami
  script:
    - echo "whereami process"
    - ls
    - echo "whereami ok"
  only:
    - main
  tags:
    - alpine-docker

unittest:
  stage: test
  script:
    - echo "start test"
    - echo "test ok"
  only:
    - main
  tags:
    - alpine-docker

katalon_test_suite:
  stage: test
  script:
    - echo "start katalon test suite"
    - echo "katalon test suite ok"
  only:
    - main
  tags:
    - alpine-docker

sonarqube:
  stage: sonarqube
  script:
    - echo "start sonarqube stage"
    - echo "sonarqube ok"
  only:
    - main
  tags:
    - alpine-docker

deploy_ssh:
  stage: deploy
  before_script:
    - echo "do some stuff before"
  script:
    - echo "deploy apps"
    - echo "deploy ok"
  only:
    - main
  tags:
    - alpine-docker
  when: manual

after_script:
  - echo "End CI/CD"
