image: maven:3.6.0-jdk-11-slim

variables:
  SOME_VAR: "some value"
  SONAR_TOKEN: "b59093f5200cd1a7575092c434998e3c3b0fc0a2"

stages:
  - build
  - test
  - sonarqube
  - deploy

before_script:
  - echo "Start CI/CD"

build:
  stage: build
  script:
    - echo "Build process"
    - cd Inquirist
    - chmod +x mvnw
    - ./mvnw -N wrapper:wrapper
    - ./mvnw -Dmaven.test.skip=true install
    - echo "Build ok"
  only:
    - main
  tags:
    - deploy
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  script:
    - echo "Unit test process"
    - cd Inquirist
    - chmod +x mvnw
    - ./mvnw -N wrapper:wrapper
    - ./mvnw clean install
    - echo "Unit test ok"
  only:
    - main
  tags:
    - deploy

sonarqube:
  stage: sonarqube
  script:
    - echo "start sonarqube stage"
    - ls
    - cd Inquirist
    - chmod +x mvnw
    - ./mvnw verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=0:0
    - echo "sonarqube ok"
  only:
    - main
  tags:
    - deploy

deploy_ssh:
  stage: deploy
  before_script:
    - apt-get update
    - apt-get install openssh-client -y
    - apt-get install sshpass -y
    - cd ..
    - ls
  script:
    - echo "deploy apps"
    - sshpass -p  "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST 'rm -r ~/inquirist' && echo old directory removed
    - sshpass -p  "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r inquirist $SSH_USER@$SSH_HOST:~/inquirist
    - sshpass -p  "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST '~/deploy.sh'
    
    #- cd Inquirist
    #- chmod +x mvnw
    #- ./mvnw spring-boot:run
    - echo "deploy ok"
  only:
    - main
  tags:
    - deploy  
  when: manual

#after_script:
#  - echo "End CI/CD"
