image: ubuntu

variables:
  SOME_VAR: "some value"
  SONAR_TOKEN: "b59093f5200cd1a7575092c434998e3c3b0fc0a2"

stages:
  - build
  - whereami
  - test
  - sonarqube
  - deploy

before_script:
  - echo "Start CI/CD"
  - apt install openjdk-11-jre-headless
  - echo "SOME_VAR = $SOME_VAR" # calls my custom variable
  - echo $CI_JOB_STAGE  # calls a predefined variable -  https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
  - echo $CI_COMMIT_SHORT_SHA # calls another predefined variable

build:
  stage: build
  script:
    - echo "Build process and tests"
    - cd Inquirist
    - chmod +x mvnw
    - ./mvnw --version
    - ./mvnw clean package
    - echo "Build ok"
  only:
    - main
  tags:
    - alpine-docker
  artifacts:
    paths:
      - target/*.jar

unittest:
  stage: test
  script:
    - echo "start test"
    - ls
    - echo "test ok"
  only:
    - main
  tags:
    - alpine-docker

katalon_test_suite:
  tags:
    - shell
  script:
    - echo "Yeet"

sonarqube:
  stage: sonarqube
  script:
    - echo "start sonarqube stage"
    - ./mvnw verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=0:0
    - echo "sonarqube ok"
  only:
    - main
  tags:
    - alpine-docker

deploy_ssh:
  stage: deploy
  before_script:
    - echo "do some stuff before"
  script:
    - echo "deploy apps"
    - echo "deploy ok"
  only:
    - main
  tags:
    - alpine-docker
  when: manual

after_script:
  - echo "End CI/CD"
