version: '3'
services:  
  spring-app:
    container_name: spring-app
    build: .
    restart: on-failure
    ports:
      - "8080:8080" 
    #environment:      
      #SPRING_DATASOURCE_USERNAME: root
      #SPRING_DATASOURCE_PASSWORD: toor
      #SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/inquirist?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
      #SPRING_DATASOURCE_DRIVERCLASSNAME: com.mysql.jdbc.Driver
    command: mvn clean spring-boot:run
    networks:
      - backend
      - frontend

volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:   