version: '3'
services:
  mysql-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # TODO START replace with your config ! 
    environment:
      MYSQL_DATABASE: inquirist
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: toor
    # TODO END replace with your config ! 
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend  

  adminer:
    image: adminer
    restart: always
    depends_on: 
      - mysql-db
    ports:
      - 8080:8080
    networks:
      - backend 
      - frontend
        
  spring-app:
    container_name: spring-app
    build: .
    restart: on-failure
    ports:
      - "8088:8080"
    depends_on: 
      - mysql-db  
    environment:      
      # TODO START replace with your config ! 
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: toor
      # TODO END replace with your config !

      # TODO START replace my_todo with your database name config ! 
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db/inquirist?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
      # TODO START replace my_todo with your database name config ! 
    command: mvn clean spring-boot:run
    networks:
      - backend
      - frontend

volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:   